## Импортируем библиотеку numpy и создаём список

In [2]:
import numpy as np

x = np.array([1, 10, 20, 30, 40, 50])
print(x)

[ 1 10 20 30 40 50]


## 2-D список (матрица)

In [23]:
y = np.array([[1, 10, 20], [30, 40, 50]])
print(y)
print('\nРазмерность массива y: ', y.shape)

[[ 1 10 20]
 [30 40 50]]

Размерность массива y:  (2, 3)


## Изменяем форму массива

In [28]:
z = np.reshape(y, (3,2))
print(z)
print('\nНе то же самое, что транспонирование!')

[[ 1 10]
 [20 30]
 [40 50]]

Не то же самое, что транспонирование!


In [33]:
print('Транспонирование:')
print(y.T)

print('\nПревращаем матрицу в вектор:')
print(np.ravel(y))

Транспонирование:
[[ 1 30]
 [10 40]
 [20 50]]

Превращаем матрицу в вектор:
[ 1 10 20 30 40 50]


## Можно эффективно выполнять операции над матрицами

In [62]:
A = np.array([[1,2,10],
              [4,5,6],
              [7,8,9]])

print('Определитель A равен: ', np.linalg.det(A))
print()
print('Ранг A равен: ', np.linalg.matrix_rank(A))
print()
print('Обратная для A матрица:\n ', np.linalg.inv(A))
print()

B = np.array([[1,0,0],
              [0,1,0],
              [0,0,1]])

C = np.matmul(A,B)
print('Произведение матриц A и B:\n', C)

Определитель A равен:  -21.00000000000001

Ранг A равен:  3

Обратная для A матрица:
  [[ 0.14285714 -2.95238095  1.80952381]
 [-0.28571429  2.9047619  -1.61904762]
 [ 0.14285714 -0.28571429  0.14285714]]

Произведение матриц A и B:
 [[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]


## Обращаемся к отдельным элементам

In [49]:
print(A[0,1]) # нумерация начинается с 0!

2


In [50]:
print(A[:,0]) # первый столбец

[1 4 7]


In [51]:
print(A[1,:]) # вторая строка

[4 5 6]


In [52]:
print(A[1:,:2]) # левый нижний квадрат 2х2

[[4 5]
 [7 8]]


In [59]:
print(A>5) # условия применяются поэлементно!

print('\n', A[A>5]) # фильтрация с помощью передачи булевой маски

[[False False  True]
 [False False  True]
 [ True  True  True]]

 [10  6  7  8  9]


In [65]:
print('A:')
print(A)

print('\nA+100:')
print(A+100)

print('\nA*2:')
print(A*2)

print('\nA**2:')
print(A**2)

A:
[[ 1  2 10]
 [ 4  5  6]
 [ 7  8  9]]

A+100:
[[101 102 110]
 [104 105 106]
 [107 108 109]]

A*2:
[[ 2  4 20]
 [ 8 10 12]
 [14 16 18]]

A**2:
[[  1   4 100]
 [ 16  25  36]
 [ 49  64  81]]
